### ISSUE TITLE
Request help for a similar case

### ISSUE THREAD

**Issue by Ya-Zahra** [alibo/cafabazaar-apk-downloader-chrome#1]
Hello, and thanks in advance.
I have a question, can you help me?
How did you discover the API to get the APK download link?
I need this for Myket, can you help me?
Myket Android app is obscured and I could not find anything with the reverse engineer.

**Comment by alibo** [comment]
I used these tools to capture the traffic and bypass the certificate pinning:

- Genymotion (Android < 7)
- Xposed Framework
  - Module: SSLUnpinning 2
  - Module: Inspeckage 
- MITMProxy


you can also use [Frida](https://frida.re/docs/android/).

**Comment by Ya-Zahra** [comment]
> 

Thanks a lot for your quickly reply.
Thank you for generously giving me your knowledge.
I'm not familiar with these but I'll try to learn them soon.
Thanks again

**Comment by Ya-Zahra** [comment]
Hi again,
Unfortunately after trying so hard, I could not configure it;
I need a complete guide on this.
*Can you give me a complete reference for this?*

My ecosystem is:
- Operating system: Windows 7
- Android Emulator: Nox App Player (with Android version 4.4.2 - with root access)
- Xposed Framework installed with these two Modules
  - SSLUnpinning 2.0
  - Inspeckage 2.3 (2.4 is incompatible for Android 4.4)
- mitmproxy 5.3.0

**Apparently many details need to be configured that I do not know**
